cp ~/yelp_old/photos_all/photo_id.jpg photos
cp ~/yelp_old/photos_all/1j09ZNPXGHA1JARtNpieAA.jpg photos
cp ~/yelp_old/photos_all/2NYal-0bhJaERAz11Xyr5w.jpg photos
cp ~/yelp_old/photos_all/3-DE2o84pbEGmHmYAzf8WQ.jpg photos
cp ~/yelp_old/photos_all/3ogxz7bfU90QOomSTk4RTQ.jpg photos
cp ~/yelp_old/photos_all/4f5siqRSJheXuSY24xORzA.jpg photos
cp ~/yelp_old/photos_all/4JH2mqCNiDPHXD1O7NJTfg.jpg photos
cp ~/yelp_old/photos_all/5MBHJFv1RklUlyZrSsJMIA.jpg photos
cp ~/yelp_old/photos_all/6aiyTFMPWFnDoDEw-PW78g.jpg photos
cp ~/yelp_old/photos_all/9oS59uoo4_xEQ4IaYHpokw.jpg photos
cp ~/yelp_old/photos_all/9S4hTgJtTI-WHcjBY1_4xg.jpg photos
cp ~/yelp_old/photos_all/aSNW289pwwE27FDp8lMUXg.jpg photos
cp ~/yelp_old/photos_all/cgnciPaJGGh880PN5ZWHUw.jpg photos
cp ~/yelp_old/photos_all/dMKV4Q78RJnMiN0YyEZptw.jpg photos
cp ~/yelp_old/photos_all/FBoumnGjZFdt9MHUohmhKA.jpg photos
cp ~/yelp_old/photos_all/F_fnOerptpOo4t_W9f6fzQ.jpg photos
cp ~/yelp_old/photos_all/ggR1ImczWI7jC5EX-09aBQ.jpg photos
cp ~/yelp_old/photos_all/grEvHhdVhJ1BflLD1ukA1w.jpg photos
cp ~/yelp_old/photos_all/hNNKyDsoQahGparz0jeXbA.jpg photos
cp ~/yelp_old/photos_all/jc2ATDtfGhmQQxW-pXpQ0g.jpg photos
cp ~/yelp_old/photos_all/Ozc8Blf5DT-LDt-_d1Zgpw.jpg photos
cp ~/yelp_old/photos_all/Qnanr0T4kV4jRHvrl0Mmuw.jpg photos
cp ~/yelp_old/photos_all/qUEeCjoyQfjFnGidFKBaKw.jpg photos
cp ~/yelp_old/photos_all/S-48KltwMr5Prpq_fV4CoA.jpg photos
cp ~/yelp_old/photos_all/ukosLRe5pRK6ncdPjlEtKg.jpg photos
cp ~/yelp_old/photos_all/vTMaEqhSABGn4xRNVOnXOw.jpg photos
cp ~/yelp_old/photos_all/vV0ACdyW3JFi4G8CC2ZiMg.jpg photos
cp ~/yelp_old/photos_all/XJBt7hp5Sjf0Z7FJYo2AHQ.jpg photos
cp ~/yelp_old/photos_all/y91ccezfbyUYgwQWvWAC9A.jpg photos
cp ~/yelp_old/photos_all/ybaGi6-ubc8PYyKmJUZOtg.jpg photos
cp ~/yelp_old/photos_all/Zgkz7XpohCoADAckvbheKA.jpg photos
cp ~/yelp_old/photos_all/ZJaOLoM9olpQUN6jckdXXQ.jpg photos
cp ~/yelp_old/photos_all/_4E2OSMvtE3vM5bPM65cdA.jpg photos
cp ~/yelp_old/photos_all/_744STVh4bz7T66El9VNNw.jpg photos
